#!/usr/bin/env python3
import argparse
import ast
import io
import re
import subprocess
import sys
import textwrap
import tokenize
from pathlib import Path

from reqctl import cite

HALVES = (("TO", "DO"), ("FIX", "ME"), ("XX", "X"), ("HA", "CK"))

MARKERS = tuple((first + rest, re.compile(rf"\b{first}[\s_-]?{rest}\b"))
                for first, rest in HALVES)

STATEMENTS = (ast.Assign, ast.AugAssign, ast.AnnAssign, ast.FunctionDef,
              ast.AsyncFunctionDef, ast.ClassDef, ast.Import, ast.ImportFrom,
              ast.Return, ast.If, ast.For, ast.While, ast.With, ast.Raise,
              ast.Assert, ast.Delete, ast.Try, ast.Pass, ast.Break,
              ast.Continue)

GOVERNED = "requirements/"
GENERATED = re.compile(r"autogenerated by|@generated|do not edit", re.I)
DECLARED = 5

PYTHON, HASH, SLASH, MARKUP = "python", "hash", "slash", "markup"

BY_NAME = {".gitattributes": HASH, ".gitignore": HASH, ".npmrc": HASH,
           ".prettierignore": HASH, ".prettierrc": SLASH, "CODEOWNERS": HASH}

BY_SUFFIX = {".py": PYTHON,
             ".bash": HASH, ".cfg": HASH, ".in": HASH, ".ini": HASH,
             ".sh": HASH, ".toml": HASH, ".txt": HASH, ".yaml": HASH,
             ".yml": HASH,
             ".cjs": SLASH, ".js": SLASH, ".json": SLASH, ".mjs": SLASH,
             ".ts": SLASH, ".tsx": SLASH,
             ".html": MARKUP, ".md": MARKUP}

ALLOWED = {
    (".github/workflows/corpus-view.yml", "# zizmor: ignore[artipacked]"),
    (".github/workflows/corpus-write.yml", "# zizmor: ignore[artipacked]"),
}

DELIMITERS = re.compile(r"\A(?:#+|//|/\*|<!--)\s*|\s*(?:\*/|-->)\Z")


def cites(body):
    stripped = DELIMITERS.sub("", body).strip()
    return bool(cite.MARKER.match(stripped))

QUOTED = re.compile(r"\"[^\"]*\"|'[^']*'")
TRAILING = re.compile(r"\S\s+(#(?:\s.*|$))")
MARKED = re.compile(r"<!--.*?-->", re.S)
EMBEDDED = re.compile(r"<(script|style)[^>]*>(.*?)</\1>", re.S)


def scanned():
    found = subprocess.run(
        ["git", "ls-files", "-z", "--cached", "--others", "--exclude-standard"],
        capture_output=True, text=True, check=False)
    if found.returncode != 0:
        raise SystemExit(f"cannot list files: {found.stderr.strip()}")
    return sorted({path for path in found.stdout.split("\0")
                   if path and not Path(path).is_symlink()})


def read(path):
    try:
        raw = Path(path).read_bytes()
    except OSError as broken:
        raise SystemExit(f"cannot read {path}: {broken}") from broken
    if b"\0" in raw:
        return None
    try:
        return raw.decode("utf-8")
    except UnicodeDecodeError as broken:
        raise SystemExit(f"cannot read {path}: {broken}") from broken


def generated(text):
    return any(GENERATED.search(line) for line in text.splitlines()[:DECLARED])


def syntax_of(path):
    held = Path(path)
    return BY_NAME.get(held.name) or BY_SUFFIX.get(held.suffix)


def python_found(path, text):
    held = []
    try:
        for token in tokenize.generate_tokens(io.StringIO(text).readline):
            if token.type != tokenize.COMMENT:
                continue
            if token.start[0] == 1 and token.string.startswith("#!"):
                continue
            held.append(("comment", token.start[0], token.start[0],
                         token.string.strip()))
    except (tokenize.TokenError, SyntaxError) as broken:
        raise SystemExit(f"cannot read {path}: {broken}") from broken
    try:
        tree = ast.parse(text, filename=str(path))
    except SyntaxError as broken:
        raise SystemExit(f"cannot read {path}: {broken}") from broken
    for node in ast.walk(tree):
        if not isinstance(node, (ast.Module, ast.ClassDef, ast.FunctionDef,
                                 ast.AsyncFunctionDef)):
            continue
        body = ast.get_docstring(node)
        if body is None:
            continue
        first = node.body[0]
        held.append(("docstring", first.lineno,
                     getattr(first, "end_lineno", first.lineno),
                     " ".join(body.split())))
    return held


def hash_found(path, text):
    held = []
    for number, line in enumerate(text.splitlines(), 1):
        bare = line.strip()
        if bare.startswith("#"):
            if number == 1 and bare.startswith("#!"):
                continue
            held.append(("comment", number, number, bare))
            continue
        blanked = QUOTED.sub(lambda span: "x" * len(span.group()), line)
        found = TRAILING.search(blanked)
        if found:
            held.append(("comment", number, number,
                         line[found.start(1):].strip()))
    return held


def past_string(text, index, number):
    quote, size = text[index], len(text)
    index += 1
    while index < size and text[index] != quote:
        if text[index] == "\\":
            index += 1
        if index < size and text[index] == "\n":
            number += 1
        index += 1
    return index + 1, number


def slash_found(path, text):
    held, index, size, number = [], 0, len(text), 1
    while index < size:
        letter = text[index]
        if letter == "\n":
            number += 1
            index += 1
        elif letter in "\"'`":
            index, number = past_string(text, index, number)
        elif text.startswith("//", index):
            stop = text.find("\n", index)
            stop = size if stop < 0 else stop
            held.append(("comment", number, number, text[index:stop].strip()))
            index = stop
        elif text.startswith("/*", index):
            stop = text.find("*/", index)
            stop = size if stop < 0 else stop + 2
            body = text[index:stop]
            end = number + body.count("\n")
            held.append(("comment", number, end, " ".join(body.split())))
            number, index = end, stop
        else:
            index += 1
    return held


def markup_found(path, text):
    held = []
    for found in MARKED.finditer(text):
        start = text.count("\n", 0, found.start()) + 1
        held.append(("comment", start, start + found.group().count("\n"),
                     " ".join(found.group().split())))
    for found in EMBEDDED.finditer(text):
        base = text.count("\n", 0, found.start(2))
        held += [(what, line + base, end + base, body)
                 for what, line, end, body in slash_found(path, found.group(2))]
    return held


FINDERS = {PYTHON: python_found, HASH: hash_found, SLASH: slash_found,
           MARKUP: markup_found}


def marked(text):
    return [name for name, pattern in MARKERS if pattern.search(text)]


def is_code(text):
    body = textwrap.dedent("\n".join(line.lstrip("#").expandtabs()
                                     for line in text.splitlines()))
    if not body.strip():
        return False
    for attempt in (body, body + "\n    pass"):
        try:
            tree = ast.parse(attempt)
        except SyntaxError:
            continue
        return any(isinstance(node, STATEMENTS)
                   or (isinstance(node, ast.Expr)
                       and isinstance(node.value, ast.Call))
                   for node in tree.body)
    return False


def runs(found, lines):
    held = []
    for line, text in found:
        skipped = lines[held[-1][0]:line - 1] if held else []
        if any(passed.strip() for passed in skipped):
            yield held
            held = []
        held.append((line, text))
    if held:
        yield held


def survey(paths, allowed=ALLOWED):
    counted, refused, used = 0, [], set()
    for path in paths:
        if path.startswith(GOVERNED):
            continue
        text = read(path)
        if text is None:
            continue
        kind = syntax_of(path)
        if kind is None:
            refused.append((path, 1, "no comment rule for this file type",
                            Path(path).suffix or Path(path).name))
            continue
        if generated(text):
            continue
        held = FINDERS[kind](path, text)
        for what, line, end, body in held:
            if (path, body) in allowed:
                used.add((path, body))
                continue
            if not (what == "comment" and cites(body)):
                counted += end - line + 1
            for marker in marked(body):
                refused.append((path, line, f"{marker} marker", body))
        if kind != PYTHON:
            continue
        lines = text.splitlines()
        for what, line, end, body in held:
            if what == "comment" and cites(body):
                lines[line - 1:end] = [""] * (end - line + 1)
        spans = [(line, body) for what, line, _, body in held
                 if what == "comment" and (path, body) not in allowed
                 and not marked(body) and not cites(body)]
        for block in runs(spans, lines):
            if is_code("\n".join(body for _, body in block)):
                refused.append((path, block[0][0], "commented-out code",
                                block[0][1]))
    for path, body in sorted(allowed - used):
        refused.append((path, 1, "exemption matches nothing here", body))
    return counted, refused


def main(ceiling):
    counted, refused = survey(scanned())
    for path, line, why, body in refused:
        print(f"::error file={path},line={line}::{why}: {body}")
    print(f"{counted} comment and docstring lines")
    if refused:
        return 1
    if counted != ceiling:
        fix = ("The code says what it does. Delete it, or say what it states "
               "in a name or the commit message." if counted > ceiling else
               "Lower the ceiling in ci.yml to hold the ground.")
        print(f"::error::the comment budget is {ceiling}; this branch has "
              f"{counted}. {fix}")
        return 1
    return 0


if __name__ == "__main__":
    parsed = argparse.ArgumentParser()
    parsed.add_argument("--max", type=int, required=True)
    sys.exit(main(parsed.parse_args().max))
