#!/usr/bin/env python3
import argparse
import ast
import io
import re
import subprocess
import sys
import textwrap
import tokenize
from pathlib import Path

from reqctl import cite

HALVES = (("TO", "DO"), ("FIX", "ME"), ("XX", "X"), ("HA", "CK"))

MARKERS = tuple((first + rest, re.compile(rf"\b{first}[\s_-]?{rest}\b"))
                for first, rest in HALVES)

STATEMENTS = (ast.Assign, ast.AugAssign, ast.AnnAssign, ast.FunctionDef,
              ast.AsyncFunctionDef, ast.ClassDef, ast.Import, ast.ImportFrom,
              ast.Return, ast.If, ast.For, ast.While, ast.With, ast.Raise,
              ast.Assert, ast.Delete, ast.Try, ast.Pass, ast.Break,
              ast.Continue)

GOVERNED = "requirements/"
GENERATED = re.compile(r"autogenerated by|@generated|do not edit", re.I)
DECLARED = 5

PYTHON, HASH, SLASH, MARKUP = "python", "hash", "slash", "markup"

BY_NAME = {".gitattributes": HASH, ".gitignore": HASH, ".npmrc": HASH,
           ".prettierignore": HASH, ".prettierrc": SLASH, "CODEOWNERS": HASH}

BY_SUFFIX = {".py": PYTHON,
             ".bash": HASH, ".cfg": HASH, ".in": HASH, ".ini": HASH,
             ".sh": HASH, ".toml": HASH, ".txt": HASH, ".yaml": HASH,
             ".yml": HASH,
             ".cjs": SLASH, ".js": SLASH, ".json": SLASH, ".mjs": SLASH,
             ".ts": SLASH, ".tsx": SLASH,
             ".html": MARKUP, ".md": MARKUP}

ALLOWED = {
    (".github/workflows/corpus-view.yml", "# zizmor: ignore[artipacked]"),
    (".github/workflows/corpus-write.yml", "# zizmor: ignore[artipacked]"),
}

DELIMITERS = re.compile(r"\A(?:#+|//|/\*|<!--)\s*|\s*(?:\*/|-->)\Z")


# @req> GUARD-27671623@3zDwoF3LwQkw 7noe76
def cites(body):
    stripped = DELIMITERS.sub("", body).strip()
    return bool(cite.MARKER.match(stripped))

# @req+ GUARD-27671623@3zDwoF3LwQkw ixyyek
QUOTED = re.compile(r"\"[^\"]*\"|'[^']*'")
TRAILING = re.compile(r"\S\s+(#(?:\s.*|$))")
MARKED = re.compile(r"<!--.*?-->", re.S)
EMBEDDED = re.compile(r"<(script|style)[^>]*>(.*?)</\1>", re.S | re.I)
WORD = re.compile(r"\d[\w.]*|[\w$]+")
BEFORE_OPERAND = frozenset({"await", "case", "delete", "do", "else", "in",
                            "instanceof", "new", "of", "return", "throw",
                            "typeof", "void", "yield"})
HEADERS = frozenset({"for", "if", "while", "with"})
FUNCTIONS = frozenset({"declaration", "expression"})
VALUES = frozenset({"group", "object", "expression"})
# @req- ixyyek


def scanned():
    found = subprocess.run(
        ["git", "ls-files", "-z", "--cached", "--others", "--exclude-standard"],
        capture_output=True, text=True, check=False)
    if found.returncode != 0:
        raise SystemExit(f"cannot list files: {found.stderr.strip()}")
    root = Path.cwd().resolve()
    held = (path for path in found.stdout.split("\0") if path)
    return sorted({path for path in held if not Path(path).is_symlink()
                   or not Path(path).resolve().is_relative_to(root)})


def read(path):
    try:
        raw = Path(path).read_bytes()
    except OSError as broken:
        raise SystemExit(f"cannot read {path}: {broken}") from broken
    if b"\0" in raw:
        return None
    try:
        return raw.decode("utf-8")
    except UnicodeDecodeError as broken:
        raise SystemExit(f"cannot read {path}: {broken}") from broken


def generated(text):
    return any(GENERATED.search(line) for line in text.splitlines()[:DECLARED])


def syntax_of(path):
    held = Path(path)
    return BY_NAME.get(held.name) or BY_SUFFIX.get(held.suffix)


# @req+ GUARD-27671623@3zDwoF3LwQkw ka4pr4
def python_found(path, text):
    held = []
    try:
        for token in tokenize.generate_tokens(io.StringIO(text).readline):
            if token.type != tokenize.COMMENT:
                continue
            if token.start[0] == 1 and token.string.startswith("#!"):
                continue
            held.append(("comment", token.start[0], token.start[0],
                         token.string.strip()))
    except (tokenize.TokenError, SyntaxError) as broken:
        raise SystemExit(f"cannot read {path}: {broken}") from broken
    try:
        tree = ast.parse(text, filename=str(path))
    except SyntaxError as broken:
        raise SystemExit(f"cannot read {path}: {broken}") from broken
    for node in ast.walk(tree):
        if not isinstance(node, (ast.Module, ast.ClassDef, ast.FunctionDef,
                                 ast.AsyncFunctionDef)):
            continue
        body = ast.get_docstring(node)
        if body is None:
            continue
        first = node.body[0]
        held.append(("docstring", first.lineno,
                     getattr(first, "end_lineno", first.lineno),
                     " ".join(body.split())))
    return held


def hash_found(path, text):
    held = []
    for number, line in enumerate(text.splitlines(), 1):
        bare = line.strip()
        if bare.startswith("#"):
            if number == 1 and bare.startswith("#!"):
                continue
            held.append(("comment", number, number, bare))
            continue
        blanked = QUOTED.sub(lambda span: "x" * len(span.group()), line)
        found = TRAILING.search(blanked)
        if found:
            held.append(("comment", number, number,
                         line[found.start(1):].strip()))
    return held


def past_string(path, text, index, number):
    quote, size, opened = text[index], len(text), number
    index += 1
    while index < size and text[index] not in (quote, "\n"):
        if text[index] == "\\":
            index += 2 if text.startswith("\r\n", index + 1) else 1
        if index < size and text[index] == "\n":
            number += 1
        index += 1
    if index >= size or text[index] != quote:
        raise SystemExit(f"cannot read {path}: the string on line {opened} "
                         "never closes")
    return index + 1, number


def past_template(path, text, index, number):
    size, opened = len(text), number
    while index < size:
        if text[index] == "`":
            return index + 1, number, False
        if text.startswith("${", index):
            return index + 2, number, True
        if text[index] == "\\":
            index += 1
        if index < size and text[index] == "\n":
            number += 1
        index += 1
    raise SystemExit(f"cannot read {path}: the template literal on line "
                     f"{opened} never closes")


def past_regex(text, index):
    size, classed = len(text), False
    index += 1
    while index < size and text[index] != "\n":
        letter = text[index]
        if letter == "\\":
            index += 1
        elif letter == "[":
            classed = True
        elif letter == "]":
            classed = False
        elif letter == "/" and not classed:
            flags = WORD.match(text, index + 1)
            if text.startswith(("//", "/*"), index) or (
                    flags and not set(flags.group()) <= set("dgimsuyv")):
                return None
            return flags.end() if flags else index + 1
        index += 1
    return None


def brace_context(parent, previous, operand):
    if parent in FUNCTIONS:
        return "block"
    if previous == "{" or previous == ":" and parent in ("block", "object"):
        return "block" if parent == "block" else "object"
    if previous in (None, ";", ")", "=>", "else") or operand:
        return "block"
    return "object"


def function_context(parent, previous, operand):
    if (operand or previous in (None, ")", "}", "else")
            or previous == ";" and parent != "header"
            or previous in ("{", ":") and parent == "block"):
        return "declaration"
    return "expression"


def slash_found(path, text, number=1, script=True):
    held, index, size = [], 0, len(text)
    nests, substitutions, operand = [], [], False
    previous, ended = None, 0
    while index < size:
        letter = text[index]
        parent = nests[-1] if nests else "block"
        if letter == "\n":
            number += 1
            index += 1
        elif letter.isspace():
            index += 1
        elif letter == "`" or (letter == "}" and substitutions
                               and substitutions[-1] == len(nests)):
            if letter == "}":
                substitutions.pop()
            index, number, opened = past_template(path, text, index + 1,
                                                  number)
            if opened:
                substitutions.append(len(nests))
            operand, previous, ended = not opened, "", index
        elif letter in "\"'":
            index, number = past_string(path, text, index, number)
            operand, previous, ended = True, "", index
        elif text.startswith("//", index) or script and (
                text.startswith("<!--", index)
                or text.startswith("-->", index)
                and (previous is None or "\n" in text[ended:index])):
            stop = text.find("\n", index)
            stop = size if stop < 0 else stop
            held.append(("comment", number, number, text[index:stop].strip()))
            index = stop
        elif text.startswith("/*", index):
            stop = text.find("*/", index)
            stop = size if stop < 0 else stop + 2
            body = text[index:stop]
            end = number + body.count("\n")
            held.append(("comment", number, end, " ".join(body.split())))
            number, index = end, stop
        elif letter == "/" and script and not operand and (
                stop := past_regex(text, index)) is not None:
            index, operand, previous, ended = stop, True, "", stop
        elif found := WORD.match(text, index):
            member = (text[index - 1:index] == "."
                      and text[index - 2:index - 1] != ".")
            if found.group() in ("class", "function") and not member:
                nests.append(function_context(parent, previous, operand))
            operand = found.group() not in BEFORE_OPERAND or member
            previous = "" if member else found.group()
            index = ended = found.end()
        elif text.startswith(("++", "--"), index):
            index = ended = index + 2
            operand, previous = True, ""
        else:
            closed = None
            if letter == "(":
                nests.append("header" if previous in HEADERS else "group")
            elif letter == "{":
                nests.append(brace_context(parent, previous, operand))
            elif letter in ")}":
                closed = nests.pop() if nests else "block"
                if closed == "block" and nests and nests[-1] in FUNCTIONS:
                    closed = nests.pop()
            elif letter == ":" and parent in FUNCTIONS:
                nests.pop()
            operand = closed in VALUES or letter == "]" or (
                letter == "!" and operand and not text[index - 1:index].isspace()
                and not text.startswith("!=", index))
            previous = "=>" if text.startswith("=>", index) else letter
            index = ended = index + len(previous)
    return held


def markup_found(path, text):
    held, outside = [], text
    for found in EMBEDDED.finditer(text):
        script = found.group(1).lower() == "script"
        held += slash_found(path, found.group(2),
                            text.count("\n", 0, found.start(2)) + 1, script)
        if script:
            outside = (outside[:found.start(2)]
                       + re.sub(r"[^\n]", " ", found.group(2))
                       + outside[found.end(2):])
    for found in MARKED.finditer(outside):
        start = outside.count("\n", 0, found.start()) + 1
        held.append(("comment", start, start + found.group().count("\n"),
                     " ".join(found.group().split())))
    return held


FINDERS = {PYTHON: python_found, HASH: hash_found, SLASH: slash_found,
           MARKUP: markup_found}
# @req- ka4pr4


def marked(text):
    return [name for name, pattern in MARKERS if pattern.search(text)]


def is_code(text):
    body = textwrap.dedent("\n".join(line.lstrip("#").expandtabs()
                                     for line in text.splitlines()))
    if not body.strip():
        return False
    for attempt in (body, body + "\n    pass"):
        try:
            tree = ast.parse(attempt)
        except SyntaxError:
            continue
        return any(isinstance(node, STATEMENTS)
                   or (isinstance(node, ast.Expr)
                       and isinstance(node.value, ast.Call))
                   for node in tree.body)
    return False


def runs(found, lines):
    held = []
    for line, text in found:
        skipped = lines[held[-1][0]:line - 1] if held else []
        if any(passed.strip() for passed in skipped):
            yield held
            held = []
        held.append((line, text))
    if held:
        yield held


# @req> GUARD-27671623@3zDwoF3LwQkw jrq67o
def survey(paths, allowed=ALLOWED):
    counted, refused, used = 0, [], set()
    for path in paths:
        if path.startswith(GOVERNED):
            continue
        text = read(path)
        if text is None:
            continue
        kind = syntax_of(path)
        if kind is None:
            refused.append((path, 1, "no comment rule for this file type",
                            Path(path).suffix or Path(path).name))
            continue
        if generated(text):
            continue
        held = FINDERS[kind](path, text)
        for what, line, end, body in held:
            if (path, body) in allowed:
                used.add((path, body))
                continue
            if not (what == "comment" and cites(body)):
                counted += end - line + 1
            for marker in marked(body):
                refused.append((path, line, f"{marker} marker", body))
        if kind != PYTHON:
            continue
        lines = text.splitlines()
        for what, line, end, body in held:
            if what == "comment" and cites(body):
                lines[line - 1:end] = [""] * (end - line + 1)
        spans = [(line, body) for what, line, _, body in held
                 if what == "comment" and (path, body) not in allowed
                 and not marked(body) and not cites(body)]
        for block in runs(spans, lines):
            if is_code("\n".join(body for _, body in block)):
                refused.append((path, block[0][0], "commented-out code",
                                block[0][1]))
    # @req> GUARD-76151755@kec8SwUpDtFd 3zx2hr
    for path, body in sorted(allowed - used):
        refused.append((path, 1, "exemption matches nothing here", body))
    return counted, refused


# @req> GUARD-27671623@3zDwoF3LwQkw hvzjkq
def main(ceiling):
    counted, refused = survey(scanned())
    for path, line, why, body in refused:
        print(f"::error file={path},line={line}::{why}: {body}")
    print(f"{counted} comment and docstring lines")
    if refused:
        return 1
    if counted != ceiling:
        fix = ("The code says what it does. Delete it, or say what it states "
               "in a name or the commit message." if counted > ceiling else
               "Lower the ceiling in ci.yml to hold the ground.")
        print(f"::error::the comment budget is {ceiling}; this branch has "
              f"{counted}. {fix}")
        return 1
    return 0


if __name__ == "__main__":
    parsed = argparse.ArgumentParser()
    parsed.add_argument("--max", type=int, required=True)
    sys.exit(main(parsed.parse_args().max))
